# Generated by Django 4.2 on 2025-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('locality', models.CharField(db_index=True, max_length=100)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['name'], name='feed_servic_name_425a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['country'], name='feed_servic_country_dd724b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['locality'], name='feed_servic_localit_b3c66f_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['region'], name='feed_servic_region_57e41b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['postal_code'], name='feed_servic_postal__a20986_idx'),
        ),
    ]
