# Generated by Django 4.2 on 2025-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='locality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='facility',
            name='postal_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['latitude', 'longitude'], name='feed_servic_latitud_6f6f33_idx'),
        ),
    ]
