# Generated by Django 4.2 on 2025-03-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='locality',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='facility',
            name='postal_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='facility',
            name='region',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['name'], name='feed_servic_name_425a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['country'], name='feed_servic_country_dd724b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['locality'], name='feed_servic_localit_b3c66f_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['region'], name='feed_servic_region_57e41b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['postal_code'], name='feed_servic_postal__a20986_idx'),
        ),
    ]
