name: CI/CD Pipeline for Facility Feed Service

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linting with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Set environment variables
        run: echo "DJANGO_SETTINGS_MODULE=facility_feed_service.settings" >> $GITHUB_ENV

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest
